spring.datasource.url=${TO_DO_API_DATASOURCE}
spring.datasource.username=${MySQL_DB_Username}
spring.datasource.password=${MySQL_DB_Password}

spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true